# Generated by Django 4.1 on 2024-08-31 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.FloatField()),
                ('turnover', models.FloatField()),
                ('ast', models.FloatField()),
                ('blk', models.FloatField()),
                ('reb_d', models.FloatField()),
                ('reb_o', models.FloatField()),
                ('pfoul', models.FloatField()),
                ('stl', models.FloatField()),
                ('reb', models.FloatField()),
                ('two', models.FloatField()),
                ('twop', models.FloatField()),
                ('trey', models.FloatField()),
                ('treyp', models.FloatField()),
                ('ft', models.FloatField()),
                ('ftp', models.FloatField()),
                ('team', models.CharField(max_length=50)),
                ('two_m', models.FloatField()),
                ('trey_m', models.FloatField()),
                ('ft_m', models.FloatField()),
                ('match', models.CharField(max_length=100)),
            ],
        ),
    ]
