# Generated by Django 4.2.5 on 2024-05-18 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('team_name', models.CharField(max_length=10)),
                ('games_played', models.IntegerField()),
                ('win', models.IntegerField()),
                ('loss', models.IntegerField()),
                ('pct', models.IntegerField()),
                ('games_behind', models.DecimalField(decimal_places=2, max_digits=3)),
                ('winning_streak', models.CharField(max_length=3)),
            ],
        ),
    ]
