# Generated by Django 4.2.5 on 2024-05-18 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamStandings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('team_name', models.CharField(max_length=10)),
                ('games_played', models.IntegerField()),
                ('wins', models.IntegerField()),
                ('losses', models.IntegerField()),
                ('pct', models.CharField(max_length=10)),
                ('games_behind', models.DecimalField(decimal_places=2, max_digits=3)),
                ('wins_losses_streak', models.CharField(max_length=3)),
            ],
        ),
        migrations.DeleteModel(
            name='TeamRank',
        ),
    ]
