# Generated by Django 4.2.5 on 2024-05-18 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0002_teamstandings_delete_teamrank'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeamStandings',
            new_name='TeamStanding',
        ),
    ]
