# Generated by Django 4.2.5 on 2024-05-18 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0003_rename_teamstandings_teamstanding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamstanding',
            name='games_behind',
            field=models.CharField(max_length=10),
        ),
    ]
