# Generated by Django 4.2.5 on 2024-05-18 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0004_alter_teamstanding_games_behind'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teamstanding',
            options={'ordering': ['rank']},
        ),
    ]
