# Generated by Django 4.2.5 on 2024-05-18 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0005_alter_teamstanding_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season_Players_Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(max_length=10)),
                ('jersey', models.IntegerField()),
                ('team', models.CharField(max_length=10)),
                ('games_played', models.IntegerField()),
                ('minutes', models.DateTimeField()),
                ('field_goals_two', models.CharField(max_length=10)),
                ('field_goals_two_attempts', models.CharField(max_length=10)),
                ('field_goals_two_pct', models.CharField(max_length=10)),
                ('field_goals_three', models.CharField(max_length=10)),
                ('field_goals_three_attempts', models.CharField(max_length=10)),
                ('field_goals_three_pct', models.CharField(max_length=10)),
                ('free_throws', models.CharField(max_length=10)),
                ('free_throws_attempts', models.CharField(max_length=10)),
                ('free_throws_pct', models.CharField(max_length=10)),
                ('points', models.CharField(max_length=10)),
                ('offensive_rebounds', models.CharField(max_length=10)),
                ('defensive_rebounds', models.CharField(max_length=10)),
                ('rebounds', models.CharField(max_length=10)),
                ('assists', models.CharField(max_length=10)),
                ('steals', models.CharField(max_length=10)),
                ('blocks', models.CharField(max_length=10)),
                ('turnovers', models.CharField(max_length=10)),
                ('fouls', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['points'],
            },
        ),
    ]
