# Generated by Django 4.2.5 on 2024-05-18 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0006_season_players_performance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season_players_performance',
            name='minutes',
            field=models.CharField(max_length=10),
        ),
    ]
