# Generated by Django 4.2.5 on 2024-05-18 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0007_alter_season_players_performance_minutes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Season_Players_Performance',
            new_name='Season_Players_Performance_22_23',
        ),
    ]
