# Generated by Django 4.2.5 on 2024-05-19 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0013_season_players_performance_20_21_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamStanding21_22',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('team_name', models.CharField(max_length=10)),
                ('games_played', models.IntegerField()),
                ('wins', models.IntegerField()),
                ('losses', models.IntegerField()),
                ('pct', models.CharField(max_length=10)),
                ('games_behind', models.CharField(max_length=10)),
                ('wins_losses_streak', models.CharField(max_length=3)),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='TeamStanding22_23',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('team_name', models.CharField(max_length=10)),
                ('games_played', models.IntegerField()),
                ('wins', models.IntegerField()),
                ('losses', models.IntegerField()),
                ('pct', models.CharField(max_length=10)),
                ('games_behind', models.CharField(max_length=10)),
                ('wins_losses_streak', models.CharField(max_length=3)),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='TeamStanding23_24',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('team_name', models.CharField(max_length=10)),
                ('games_played', models.IntegerField()),
                ('wins', models.IntegerField()),
                ('losses', models.IntegerField()),
                ('pct', models.CharField(max_length=10)),
                ('games_behind', models.CharField(max_length=10)),
                ('wins_losses_streak', models.CharField(max_length=3)),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
        migrations.RenameModel(
            old_name='TeamStanding',
            new_name='TeamStanding20_21',
        ),
    ]
