# Generated by Django 4.2.11 on 2024-05-20 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0015_t1_teamstanding20_21_t1_teamstanding21_22_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='T1_TeamStanding20_21',
        ),
        migrations.DeleteModel(
            name='T1_TeamStanding21_22',
        ),
        migrations.DeleteModel(
            name='T1_TeamStanding22_23',
        ),
        migrations.DeleteModel(
            name='T1_TeamStanding23_24',
        ),
    ]
