# Generated by Django 4.2.11 on 2024-05-20 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0017_t1_teamstanding20_21_t1_teamstanding21_22_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='t1_teamstanding20_21',
            options={},
        ),
        migrations.AlterModelOptions(
            name='t1_teamstanding21_22',
            options={},
        ),
        migrations.AlterModelOptions(
            name='t1_teamstanding22_23',
            options={},
        ),
        migrations.AlterModelOptions(
            name='t1_teamstanding23_24',
            options={},
        ),
        migrations.AlterModelOptions(
            name='teamstanding20_21',
            options={},
        ),
        migrations.AlterModelOptions(
            name='teamstanding21_22',
            options={},
        ),
        migrations.AlterModelOptions(
            name='teamstanding22_23',
            options={},
        ),
        migrations.AlterModelOptions(
            name='teamstanding23_24',
            options={},
        ),
    ]
