# Generated by Django 4.2.11 on 2024-05-28 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0019_t1_season_players_performance_21_22_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='season_players_performance_20_21',
            name='field_goals_three_made',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='season_players_performance_20_21',
            name='field_goals_two_made',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='season_players_performance_21_22',
            name='field_goals_three_made',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='season_players_performance_21_22',
            name='field_goals_two_made',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='season_players_performance_22_23',
            name='field_goals_three_made',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='season_players_performance_22_23',
            name='field_goals_two_made',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='season_players_performance_23_24',
            name='field_goals_three_made',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='season_players_performance_23_24',
            name='field_goals_two_made',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='t1_season_players_performance_21_22',
            name='field_goals_three_made',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='t1_season_players_performance_21_22',
            name='field_goals_two_made',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='t1_season_players_performance_22_23',
            name='field_goals_three_made',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='t1_season_players_performance_22_23',
            name='field_goals_two_made',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='t1_season_players_performance_23_24',
            name='field_goals_three_made',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='t1_season_players_performance_23_24',
            name='field_goals_two_made',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='season_players_performance_20_21',
            name='field_goals_three',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='season_players_performance_21_22',
            name='field_goals_three',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='season_players_performance_22_23',
            name='field_goals_three',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='season_players_performance_23_24',
            name='field_goals_three',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='t1_season_players_performance_21_22',
            name='field_goals_three',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='t1_season_players_performance_22_23',
            name='field_goals_three',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='t1_season_players_performance_23_24',
            name='field_goals_three',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
