# Generated by Django 4.2.11 on 2024-05-28 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0020_season_players_performance_20_21_field_goals_three_made_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season_players_performance_20_21',
            name='field_goals_three_attempts',
        ),
        migrations.RemoveField(
            model_name='season_players_performance_20_21',
            name='field_goals_two_attempts',
        ),
        migrations.RemoveField(
            model_name='season_players_performance_21_22',
            name='field_goals_three_attempts',
        ),
        migrations.RemoveField(
            model_name='season_players_performance_21_22',
            name='field_goals_two_attempts',
        ),
        migrations.RemoveField(
            model_name='season_players_performance_22_23',
            name='field_goals_three_attempts',
        ),
        migrations.RemoveField(
            model_name='season_players_performance_22_23',
            name='field_goals_two_attempts',
        ),
        migrations.RemoveField(
            model_name='season_players_performance_23_24',
            name='field_goals_three_attempts',
        ),
        migrations.RemoveField(
            model_name='season_players_performance_23_24',
            name='field_goals_two_attempts',
        ),
        migrations.RemoveField(
            model_name='t1_season_players_performance_21_22',
            name='field_goals_three_attempts',
        ),
        migrations.RemoveField(
            model_name='t1_season_players_performance_21_22',
            name='field_goals_two_attempts',
        ),
        migrations.RemoveField(
            model_name='t1_season_players_performance_22_23',
            name='field_goals_three_attempts',
        ),
        migrations.RemoveField(
            model_name='t1_season_players_performance_22_23',
            name='field_goals_two_attempts',
        ),
        migrations.RemoveField(
            model_name='t1_season_players_performance_23_24',
            name='field_goals_three_attempts',
        ),
        migrations.RemoveField(
            model_name='t1_season_players_performance_23_24',
            name='field_goals_two_attempts',
        ),
    ]
