# Generated by Django 4.2.11 on 2024-05-28 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0022_season_players_performance_20_21_all_goals_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='season_players_performance_20_21',
            name='All_goals_made',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='season_players_performance_20_21',
            name='All_goals_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='season_players_performance_21_22',
            name='All_goals_made',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='season_players_performance_21_22',
            name='All_goals_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='season_players_performance_22_23',
            name='All_goals_made',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='season_players_performance_22_23',
            name='All_goals_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='season_players_performance_23_24',
            name='All_goals_made',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='season_players_performance_23_24',
            name='All_goals_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='t1_season_players_performance_21_22',
            name='All_goals_made',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='t1_season_players_performance_21_22',
            name='All_goals_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='t1_season_players_performance_22_23',
            name='All_goals_made',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='t1_season_players_performance_22_23',
            name='All_goals_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='t1_season_players_performance_23_24',
            name='All_goals_made',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='t1_season_players_performance_23_24',
            name='All_goals_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
