# Generated by Django 4.2.11 on 2024-05-28 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0024_t1_season_teams_performance_22_23_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='T1_Season_teams_Performance_21_22',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=10)),
                ('gp', models.CharField(max_length=10)),
                ('minutes', models.TimeField()),
                ('All_goals_made', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('All_goals', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('All_goals_pct', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('field_goals_two_made', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('field_goals_two', models.DecimalField(decimal_places=2, max_digits=10)),
                ('field_goals_two_pct', models.DecimalField(decimal_places=2, max_digits=10)),
                ('field_goals_three_made', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('field_goals_three', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('field_goals_three_pct', models.DecimalField(decimal_places=2, max_digits=10)),
                ('free_throws', models.DecimalField(decimal_places=2, max_digits=10)),
                ('free_throws_attempts', models.DecimalField(decimal_places=2, max_digits=10)),
                ('free_throws_pct', models.DecimalField(decimal_places=2, max_digits=10)),
                ('points', models.DecimalField(decimal_places=2, max_digits=10)),
                ('offensive_rebounds', models.DecimalField(decimal_places=2, max_digits=10)),
                ('defensive_rebounds', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rebounds', models.DecimalField(decimal_places=2, max_digits=10)),
                ('assists', models.DecimalField(decimal_places=2, max_digits=10)),
                ('steals', models.DecimalField(decimal_places=2, max_digits=10)),
                ('blocks', models.DecimalField(decimal_places=2, max_digits=10)),
                ('turnovers', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fouls', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
