# Generated by Django 4.2.11 on 2024-06-12 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0025_t1_season_teams_performance_21_22'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season_players_performance_20_21',
            name='games_played',
        ),
        migrations.RemoveField(
            model_name='season_players_performance_20_21',
            name='minutes',
        ),
        migrations.RemoveField(
            model_name='season_players_performance_21_22',
            name='games_played',
        ),
        migrations.RemoveField(
            model_name='season_players_performance_21_22',
            name='minutes',
        ),
        migrations.RemoveField(
            model_name='season_players_performance_22_23',
            name='games_played',
        ),
        migrations.RemoveField(
            model_name='season_players_performance_22_23',
            name='minutes',
        ),
        migrations.RemoveField(
            model_name='season_players_performance_23_24',
            name='games_played',
        ),
        migrations.RemoveField(
            model_name='season_players_performance_23_24',
            name='minutes',
        ),
        migrations.RemoveField(
            model_name='t1_season_players_performance_21_22',
            name='games_played',
        ),
        migrations.RemoveField(
            model_name='t1_season_players_performance_21_22',
            name='minutes',
        ),
        migrations.RemoveField(
            model_name='t1_season_players_performance_22_23',
            name='games_played',
        ),
        migrations.RemoveField(
            model_name='t1_season_players_performance_22_23',
            name='minutes',
        ),
        migrations.RemoveField(
            model_name='t1_season_players_performance_23_24',
            name='games_played',
        ),
        migrations.RemoveField(
            model_name='t1_season_players_performance_23_24',
            name='minutes',
        ),
    ]
