# Generated by Django 4.2.11 on 2024-06-14 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0026_remove_season_players_performance_20_21_games_played_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='season_players_performance_20_21',
            old_name='free_throws_attempts',
            new_name='free_throws_made',
        ),
        migrations.RenameField(
            model_name='season_players_performance_21_22',
            old_name='free_throws_attempts',
            new_name='free_throws_made',
        ),
        migrations.RenameField(
            model_name='season_players_performance_22_23',
            old_name='free_throws_attempts',
            new_name='free_throws_made',
        ),
        migrations.RenameField(
            model_name='season_players_performance_23_24',
            old_name='free_throws_attempts',
            new_name='free_throws_made',
        ),
        migrations.RenameField(
            model_name='t1_season_players_performance_21_22',
            old_name='free_throws_attempts',
            new_name='free_throws_made',
        ),
        migrations.RenameField(
            model_name='t1_season_players_performance_22_23',
            old_name='free_throws_attempts',
            new_name='free_throws_made',
        ),
        migrations.RenameField(
            model_name='t1_season_players_performance_23_24',
            old_name='free_throws_attempts',
            new_name='free_throws_made',
        ),
        migrations.RenameField(
            model_name='t1_season_teams_performance_21_22',
            old_name='free_throws_attempts',
            new_name='free_throws_made',
        ),
        migrations.RenameField(
            model_name='t1_season_teams_performance_22_23',
            old_name='free_throws_attempts',
            new_name='free_throws_made',
        ),
        migrations.RenameField(
            model_name='t1_season_teams_performance_23_24',
            old_name='free_throws_attempts',
            new_name='free_throws_made',
        ),
        migrations.RemoveField(
            model_name='t1_season_teams_performance_21_22',
            name='gp',
        ),
        migrations.RemoveField(
            model_name='t1_season_teams_performance_21_22',
            name='minutes',
        ),
        migrations.RemoveField(
            model_name='t1_season_teams_performance_22_23',
            name='gp',
        ),
        migrations.RemoveField(
            model_name='t1_season_teams_performance_22_23',
            name='minutes',
        ),
        migrations.RemoveField(
            model_name='t1_season_teams_performance_23_24',
            name='gp',
        ),
        migrations.RemoveField(
            model_name='t1_season_teams_performance_23_24',
            name='minutes',
        ),
    ]
