# Generated by Django 4.2.5 on 2024-06-15 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0028_p_season_teams_performance_20_21_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='P_Season_teams_Performance_20_21',
        ),
        migrations.DeleteModel(
            name='P_Season_teams_Performance_21_22',
        ),
        migrations.DeleteModel(
            name='P_Season_teams_Performance_22_23',
        ),
        migrations.DeleteModel(
            name='P_Season_teams_Performance_23_24',
        ),
    ]
