# Generated by Django 4.2.5 on 2024-06-18 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0030_p_season_teams_performance_20_21_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='p_season_players_performance_20_21',
            name='game_played',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='p_season_players_performance_20_21',
            name='minutes',
            field=models.CharField(default='00:00', max_length=5),
        ),
        migrations.AddField(
            model_name='p_season_players_performance_21_22',
            name='game_played',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='p_season_players_performance_21_22',
            name='minutes',
            field=models.CharField(default='00:00', max_length=5),
        ),
        migrations.AddField(
            model_name='p_season_players_performance_22_23',
            name='game_played',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='p_season_players_performance_22_23',
            name='minutes',
            field=models.CharField(default='00:00', max_length=5),
        ),
        migrations.AddField(
            model_name='p_season_players_performance_23_24',
            name='game_played',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='p_season_players_performance_23_24',
            name='minutes',
            field=models.CharField(default='00:00', max_length=5),
        ),
        migrations.AddField(
            model_name='t1_season_players_performance_21_22',
            name='game_played',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='t1_season_players_performance_21_22',
            name='minutes',
            field=models.CharField(default='00:00', max_length=5),
        ),
        migrations.AddField(
            model_name='t1_season_players_performance_22_23',
            name='game_played',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='t1_season_players_performance_22_23',
            name='minutes',
            field=models.CharField(default='00:00', max_length=5),
        ),
        migrations.AddField(
            model_name='t1_season_players_performance_23_24',
            name='game_played',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='t1_season_players_performance_23_24',
            name='minutes',
            field=models.CharField(default='00:00', max_length=5),
        ),
    ]
