# Generated by Django 4.1 on 2024-09-01 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0031_p_season_players_performance_20_21_game_played_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='p_season_players_performance_20_21',
            name='pos',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='p_season_players_performance_21_22',
            name='pos',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='p_season_players_performance_22_23',
            name='pos',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='p_season_players_performance_23_24',
            name='pos',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='t1_season_players_performance_21_22',
            name='pos',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='t1_season_players_performance_22_23',
            name='pos',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='t1_season_players_performance_23_24',
            name='pos',
            field=models.CharField(default='', max_length=10),
        ),
    ]
