# Generated by Django 4.1 on 2024-09-04 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0032_p_season_players_performance_20_21_pos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='p_season_players_performance_20_21',
            name='position',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='p_season_players_performance_21_22',
            name='position',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='p_season_players_performance_22_23',
            name='position',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='p_season_players_performance_23_24',
            name='position',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='t1_season_players_performance_21_22',
            name='position',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='t1_season_players_performance_22_23',
            name='position',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='t1_season_players_performance_23_24',
            name='position',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
