# Generated by Django 4.1 on 2024-09-04 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0033_p_season_players_performance_20_21_position_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='p_season_players_performance_20_21',
            name='pos',
        ),
        migrations.RemoveField(
            model_name='p_season_players_performance_21_22',
            name='pos',
        ),
        migrations.RemoveField(
            model_name='p_season_players_performance_22_23',
            name='pos',
        ),
        migrations.RemoveField(
            model_name='p_season_players_performance_23_24',
            name='pos',
        ),
        migrations.RemoveField(
            model_name='t1_season_players_performance_21_22',
            name='pos',
        ),
        migrations.RemoveField(
            model_name='t1_season_players_performance_22_23',
            name='pos',
        ),
        migrations.RemoveField(
            model_name='t1_season_players_performance_23_24',
            name='pos',
        ),
    ]
