# Generated by Django 4.1 on 2024-09-19 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0035_alter_p_season_players_performance_20_21_minutes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_home', models.CharField(max_length=100)),
                ('team_away', models.CharField(max_length=100)),
                ('game_date', models.DateTimeField()),
                ('location', models.CharField(max_length=200)),
            ],
        ),
    ]
