# Generated by Django 5.1.1 on 2024-10-27 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0038_p_season_teams_final_performance_22_23_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='schedule',
            table='ScheduleP',
        ),
    ]
