# Generated by Django 5.1.1 on 2024-10-27 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0039_alter_schedule_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_home', models.CharField(max_length=100)),
                ('team_away', models.CharField(max_length=100)),
                ('game_date', models.DateTimeField()),
                ('location', models.CharField(max_length=200)),
            ],
        ),
    ]
