# Generated by Django 4.1 on 2024-10-23 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0039_p_season_players_performance_24_25_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TPBL_Season_Players_Performance_24_25',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(max_length=10)),
                ('jersey', models.IntegerField()),
                ('position', models.CharField(default='0', max_length=10)),
                ('team', models.CharField(max_length=10)),
                ('game_played', models.IntegerField(default=0)),
                ('minutes', models.CharField(default='00:00:00', max_length=5)),
                ('points', models.DecimalField(decimal_places=2, max_digits=10)),
                ('All_goals_made', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('All_goals', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('All_goals_pct', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('field_goals_two_made', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('field_goals_two', models.DecimalField(decimal_places=2, max_digits=10)),
                ('field_goals_two_pct', models.DecimalField(decimal_places=2, max_digits=10)),
                ('field_goals_three_made', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('field_goals_three', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('field_goals_three_pct', models.DecimalField(decimal_places=2, max_digits=10)),
                ('free_throws_made', models.DecimalField(decimal_places=2, max_digits=10)),
                ('free_throws', models.DecimalField(decimal_places=2, max_digits=10)),
                ('free_throws_pct', models.DecimalField(decimal_places=2, max_digits=10)),
                ('offensive_rebounds', models.DecimalField(decimal_places=2, max_digits=10)),
                ('defensive_rebounds', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rebounds', models.DecimalField(decimal_places=2, max_digits=10)),
                ('assists', models.DecimalField(decimal_places=2, max_digits=10)),
                ('steals', models.DecimalField(decimal_places=2, max_digits=10)),
                ('blocks', models.DecimalField(decimal_places=2, max_digits=10)),
                ('turnovers', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fouls', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TPBL_Season_Teams_Performance_24_25',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=10)),
                ('points', models.DecimalField(decimal_places=2, max_digits=10)),
                ('All_goals_made', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('All_goals', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('All_goals_pct', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('field_goals_two_made', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('field_goals_two', models.DecimalField(decimal_places=2, max_digits=10)),
                ('field_goals_two_pct', models.DecimalField(decimal_places=2, max_digits=10)),
                ('field_goals_three_made', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('field_goals_three', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('field_goals_three_pct', models.DecimalField(decimal_places=2, max_digits=10)),
                ('free_throws_made', models.DecimalField(decimal_places=2, max_digits=10)),
                ('free_throws', models.DecimalField(decimal_places=2, max_digits=10)),
                ('free_throws_pct', models.DecimalField(decimal_places=2, max_digits=10)),
                ('offensive_rebounds', models.DecimalField(decimal_places=2, max_digits=10)),
                ('defensive_rebounds', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rebounds', models.DecimalField(decimal_places=2, max_digits=10)),
                ('assists', models.DecimalField(decimal_places=2, max_digits=10)),
                ('steals', models.DecimalField(decimal_places=2, max_digits=10)),
                ('blocks', models.DecimalField(decimal_places=2, max_digits=10)),
                ('turnovers', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fouls', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
