# Generated by Django 4.1 on 2024-10-28 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0040_schedulet'),
        ('cat', '0040_tpbl_season_players_performance_24_25_and_more'),
    ]

    operations = [
    ]
