# Generated by Django 4.1 on 2024-11-04 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0041_merge_20241028_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='P_TeamStanding24_25',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('team_name', models.CharField(max_length=10)),
                ('games_played', models.IntegerField()),
                ('wins', models.IntegerField()),
                ('losses', models.IntegerField()),
                ('pct', models.CharField(max_length=10)),
                ('games_behind', models.CharField(max_length=10)),
                ('wins_losses_streak', models.CharField(max_length=3)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
