# Generated by Django 4.1 on 2024-11-10 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0043_t1_teamsteanding24_25'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='T1_TeamSteanding24_25',
            new_name='T1_TeamStanding24_25',
        ),
    ]
