# Generated by Django 5.1.1 on 2024-11-13 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0045_allplayerdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField(max_length=100, verbose_name='比賽場次')),
                ('team_name', models.CharField(max_length=100, verbose_name='球隊名稱')),
                ('is_home', models.BooleanField(default=False, verbose_name='是否為主場')),
                ('two_m', models.IntegerField(verbose_name='兩分球命中')),
                ('two', models.IntegerField(verbose_name='兩分球出手')),
                ('twop', models.FloatField(verbose_name='兩分球命中率')),
                ('trey_m', models.IntegerField(verbose_name='三分球命中')),
                ('trey', models.IntegerField(verbose_name='三分球出手')),
                ('treyp', models.FloatField(verbose_name='三分球命中率')),
                ('ft_m', models.IntegerField(verbose_name='罰球命中')),
                ('ft', models.IntegerField(verbose_name='罰球出手')),
                ('ftp', models.FloatField(verbose_name='罰球命中率')),
                ('points', models.IntegerField(verbose_name='得分')),
                ('reb', models.IntegerField(verbose_name='籃板')),
                ('reb_o', models.IntegerField(verbose_name='進攻籃板')),
                ('reb_d', models.IntegerField(verbose_name='防守籃板')),
                ('ast', models.IntegerField(verbose_name='助攻')),
                ('stl', models.IntegerField(verbose_name='抄截')),
                ('blk', models.IntegerField(verbose_name='阻攻')),
                ('turnover', models.IntegerField(verbose_name='失誤')),
                ('pfoul', models.IntegerField(verbose_name='犯規')),
            ],
        ),
    ]
